const mongoose = require('mongoose');

/** File phụ đề của một video theo từng ngôn ngữ. */
const subtitleSchema = new mongoose.Schema(
  {
    videoId: { type: mongoose.Schema.Types.ObjectId, ref: 'Video', required: true },
    lang: { type: String, required: true },
    langLabel: { type: String, default: null },
    format: { type: String, enum: ['srt', 'vtt'], default: 'vtt' },
    url: { type: String, required: true },
    isAutoGenerated: { type: Boolean, default: true },
    isOriginal: { type: Boolean, default: false }, // phụ đề của ngôn ngữ gốc
  },
  { timestamps: true }
);

subtitleSchema.index({ videoId: 1, lang: 1 }, { unique: true });

module.exports = mongoose.model('Subtitle', subtitleSchema);
