const mongoose = require('mongoose');

/**
 * Subtitle — file phụ đề SRT/VTT cho từng ngôn ngữ
 */
const subtitleSchema = new mongoose.Schema(
  {
    videoId: { type: mongoose.Schema.Types.ObjectId, ref: 'Video', required: true },
    lang: { type: String, required: true }, // VD: 'vi', 'en', 'zh'
    langLabel: { type: String }, // VD: 'Tiếng Việt', 'English'
    format: { type: String, enum: ['srt', 'vtt'], default: 'vtt' },
    url: { type: String, required: true }, // S3 URL
    isAutoGenerated: { type: Boolean, default: true }, // từ AI hay upload tay
  },
  { timestamps: true }
);

subtitleSchema.index({ videoId: 1, lang: 1 }, { unique: true });

module.exports = mongoose.model('Subtitle', subtitleSchema);
