const Subtitle = require('../models/Subtitle');
const storageService = require('./storage.service');
const { SUPPORTED_LANGS } = require('../utils/constants');

const langLabel = (code) => SUPPORTED_LANGS.find((l) => l.code === code)?.name || code;

/** 75.23 giây -> "00:01:15.230" theo định dạng WebVTT. */
function formatTimestamp(seconds, separator = '.') {
  const total = Math.max(0, Number(seconds) || 0);
  const h = String(Math.floor(total / 3600)).padStart(2, '0');
  const m = String(Math.floor((total % 3600) / 60)).padStart(2, '0');
  const s = String(Math.floor(total % 60)).padStart(2, '0');
  const ms = String(Math.round((total % 1) * 1000)).padStart(3, '0');
  return `${h}:${m}:${s}${separator}${ms}`;
}

function buildVTT(segments, textKey = 'text') {
  const lines = ['WEBVTT', ''];
  segments.forEach((seg, index) => {
    const text = (seg[textKey] || seg.text || '').trim();
    if (!text) return;
    lines.push(String(index + 1));
    lines.push(`${formatTimestamp(seg.start)} --> ${formatTimestamp(seg.end)}`);
    lines.push(text);
    lines.push('');
  });
  return lines.join('\n');
}

function buildSRT(segments, textKey = 'text') {
  const blocks = [];
  segments.forEach((seg, index) => {
    const text = (seg[textKey] || seg.text || '').trim();
    if (!text) return;
    blocks.push(
      `${index + 1}\n${formatTimestamp(seg.start, ',')} --> ${formatTimestamp(seg.end, ',')}\n${text}\n`
    );
  });
  return blocks.join('\n');
}

/** Sinh file VTT, đẩy lên S3 và ghi nhận vào collection Subtitle. */
async function createSubtitle(videoId, lang, segments, { textKey = 'text', isOriginal = false } = {}) {
  const content = buildVTT(segments, textKey);
  const url = await storageService.uploadBuffer(
    `${videoId}/subtitles/${lang}.vtt`,
    Buffer.from(content, 'utf8'),
    'text/vtt',
    storageService.BUCKETS.AUDIO
  );

  const subtitle = await Subtitle.findOneAndUpdate(
    { videoId, lang },
    { langLabel: langLabel(lang), format: 'vtt', url, isAutoGenerated: true, isOriginal },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );

  return subtitle;
}

async function getSubtitles(videoId) {
  return Subtitle.find({ videoId }).lean();
}

module.exports = { buildVTT, buildSRT, createSubtitle, getSubtitles, formatTimestamp, langLabel };
