const express = require('express');
const router = express.Router();
const adminController = require('../controllers/admin.controller');
const { authenticate, requireRole } = require('../middlewares/auth.middleware');
router.use(authenticate, requireRole('admin'));
router.get('/stats', adminController.getStats);
router.get('/users', adminController.getUsers);
router.post('/users/:id/ban', adminController.banUser);
router.post('/users/:id/unban', adminController.unbanUser);
router.post('/users/:id/verify', adminController.verifyUser);
router.get('/videos', adminController.getVideos);
router.delete('/videos/:id', adminController.removeVideo);
router.post('/videos/:id/approve', adminController.approveVideo);
router.get('/videos/flagged', adminController.getFlaggedVideos);
router.get('/audit-logs', adminController.getAuditLogs);
module.exports = router;