const router = require('express').Router();
router.use('/auth', require('./auth.routes'));
router.use('/users', require('./user.routes'));
router.use('/videos', require('./video.routes'));
router.use('/comments', require('./comment.routes'));
router.use('/feed', require('./feed.routes'));
router.use('/notifications', require('./notification.routes'));
router.use('/dubbing', require('./dubbing.routes'));
router.use('/admin', require('./admin.routes'));
module.exports = router;