const express = require('express');
const router = express.Router();
const userController = require('../controllers/user.controller');
const { authenticate } = require('../middlewares/auth.middleware');
router.get('/search', userController.searchUsers);
router.get('/:username', userController.getProfile);
router.patch('/me', authenticate, userController.updateProfile);
router.delete('/me', authenticate, userController.deleteAccount);
router.get('/:id/videos', userController.getUserVideos);
module.exports = router;